package cite.ansteph.ponda.template;

/**
 * Created by loicstephan on 2018/03/02.
 */

public class MeetingTemplate {


    String ATTENDANCE_REGISTER ="ATTENDANCE REGISTER";
    String APOLOGIES ="APOLOGIES";
    String MINUTES_PREVIOUS_MEETING="MINUTES OF PREVIOUS MEETING";
    String MATTERS_ARISING="MATTERS ARISING";
    String CONTRACT_DETAILS="CONTRACT DETAILS";
    String PROGRAMME="PROGRAMME";
    String DELAYS="DELAYS";
    String CASH_FLOW="CASH FLOW";
    String PAYMENT_CERTIFICATES="PAYMENT CERTIFICATES";
    String PROGRESS="PROGRESS";
    String DAILY_WORK_SCHEDULES="DAILY WORK SCHEDULES";
    String PLANT_LABOUR_REPORT="PLANT AND LABOUR REPORT";
    String DRAWINGS_ISSUED="DRAWINGS ISSUED";
    String INFORMATION_REQUIRED="INFORMATION REQUIRED";
    String NOMINATED_SUB_CONTRACTORS="NOMINATED SUB CONTRACTORS";
    String DOMESTIC_SUB_CONTRACTORS="DOMESTIC SUB CONTRACTORS";
    String STRUCTURAL="STRUCTURAL";
    String INDEPENDENT_DEVELOPMENT_TRUST="INDEPENDENT DEVELOPMENT TRUST";
    String SOCIAL_FACILITATION="SOCIAL FACILITATION";
    String CONTRACT_INSTRUCTIONS="CONTRACT INSTRUCTIONS";
    String VARIATION_ORDERS="VARIATION ORDERS";
    String HEALTH_SAFETY="HEALTH & SAFETY";
    String COMMISSIONING_TESTING="COMMISSIONING & TESTING";
    String GENERAL="GENERAL";
    String APPROVAL_MINUTES="APPROVAL OF MINUTES";

    String MEETINGS="MEETINGS";





    String [] Template = new String[]{ATTENDANCE_REGISTER,
     APOLOGIES ,
     MINUTES_PREVIOUS_MEETING,
     MATTERS_ARISING,
     CONTRACT_DETAILS,
     PROGRAMME,
     DELAYS,
     CASH_FLOW,
     PAYMENT_CERTIFICATES,
     PROGRESS,
     DAILY_WORK_SCHEDULES,
     PLANT_LABOUR_REPORT,
     DRAWINGS_ISSUED,
     INFORMATION_REQUIRED,
     NOMINATED_SUB_CONTRACTORS,
     DOMESTIC_SUB_CONTRACTORS,
     STRUCTURAL,
     INDEPENDENT_DEVELOPMENT_TRUST,
     SOCIAL_FACILITATION,
     CONTRACT_INSTRUCTIONS,
     VARIATION_ORDERS,
     HEALTH_SAFETY,
     COMMISSIONING_TESTING,
     GENERAL,
     APPROVAL_MINUTES,

     MEETINGS};










}
